---
- name: Add EPEL repo
  dnf:
    name: 
      - epel-release
      - dnf-plugins-core
    state: present

- name: Add OpenHPC repo
  dnf:
    name: http://repos.openhpc.community/OpenHPC/3/EL_9/x86_64/ohpc-release-3-1.el9.x86_64.rpm
    disable_gpg_check: true
    state: present

- name: Install OpenHPC packages
  dnf:
    name:
      - ohpc-base
      - ohpc-slurm-client
      - lmod-ohpc
    state: present

- name: Install user packages
  dnf:
    name:
      - firewalld
    state: present
