---
- name: Install Openstack client via pip
  pip:
    name: 
      - cryptography==3.3.2  # workaround: https://github.com/Azure/azure-cli/issues/16858
      - python-openstackclient
      - python-openstacksdk
    state: present
